### ISSUE TITLE
BeerJS #1: Капчо бар

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#1]
4 October 2017
[Капчо бар](https://kapcho.ru)
[Rozy Luxemburg, 8/10](https://yandex.ru/maps/-/CBUcv4xlhD)
8:00 p.m.

**Comment by partyordie** [comment]
`:octocat: `

**Comment by evilj0e** [comment]
:octocat:

**Comment by vaseker** [comment]
:octocat:

**Comment by evilj0e** [comment]
:octocat:

**Comment by partyordie** [comment]
:octocat:

**Comment by devilportez** [comment]
:octocat:

**Comment by He4eT** [comment]
:octocat:

**Comment by Blackheart340** [comment]
:octocat:

**Comment by evilj0e** [comment]
Ебой! Вот и прошёл наш первый BeerJS 🎉🎉🎉

Было интересно узнать про грэпплинг, поболтать о “русском робокопе” Фёдоре, ютюбе, фронтенд юности и гитарках.
Спасибо всем, кто пришёл. 

Подписывайтесь на обновления репозитория, приглашайте друзей и знакомых. Увидимся через 2 недели. 🚀

Ссылки, которые обсуждали:
* Робот Фёдор: https://youtu.be/3KEOx9SV1fU
* Фронтенд Юность: https://soundcloud.com/frontend_u
* Короткометражки “Бегущего по лезвию”: https://youtu.be/QsNM8YyBLFk https://youtu.be/HBomtD6YyT4

![img_20171004_230406-01](https://user-images.githubusercontent.com/914429/31213679-3714b58c-a9c1-11e7-8962-97ae5a51701b.jpeg)
