### ISSUE TITLE
BeerJS #10: The Yankee Bar

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#10]
21 February 2018
[The Yankee Bar](https://vk.com/theyankeebar)
[Tolmacheva, 25](https://yandex.ru/maps/-/CBUiFXrLtA)
8:00 p.m.

[Add to calendar](https://www.dropbox.com/s/vp6m93yrrqmwp50/BeerJS-10-The-Yankee-Bar.ics?dl=1)

If you come, let us know by commenting the issue.

**Comment by xiiivii** [comment]
🥇

**Comment by evilj0e** [comment]
🥇

**Comment by partyordie** [comment]
🐔

**Comment by monrus** [comment]
:beers:

**Comment by Iller45** [comment]
:heavy_plus_sign:

**Comment by vaseker** [comment]
+2 лица

**Comment by BolotskyDev** [comment]
+1

**Comment by Azomas** [comment]
:hamburger:

**Comment by antonlyaptsev** [comment]
🌴

**Comment by nulladdict** [comment]
🦀

**Comment by LeMarck** [comment]
🛩

**Comment by iAdramelk** [comment]
👽

**Comment by Ivan-Feofanov** [comment]
:cactus:

**Comment by gibson** [comment]
🚴🏿

**Comment by v3new** [comment]
🏄‍♂️

**Comment by evilj0e** [comment]
Ае! Вчера прошла 10 встреча BeerJS.

Обсудили кто такой фулстек, как написать бесконечно масштабируемое приложение без дыр, про майнер в фавиконке, нужны ли код-кэмпы в РФ и зашкварно ли участвовать на олимпиаде, если ничего не умеешь ♥️

Спасибо всем, кто пришёл. До встречи через 2 недели. 💅

Ссылочки из общения:
• Майнер в фавиконе: https://twitter.com/xbs/status/963796410100604929
• Перформанц: https://calendar.perfplanet.com/2017/performance-insurance
• Как написать приложение без дыр и бесконечно масштабируемое: https://github.com/kelseyhightower/nocode
• Foreign fetch: https://developers.google.com/web/updates/2016/09/foreign-fetch
• Треш видео по айти тематике: https://www.youtube.com/channel/UC9hBi-d-CKFU55XRd1JP3LA
• Квейк в виар: https://www.youtube.com/watch?v=ehoEJqZVFB0
• Лыжница на Олимпиаде: https://esquire.ru/articles/43162-skier-without-tricks/

Фоточки: https://www.dropbox.com/sh/cc5h1vom975mtif/AADEFgQycXovNwhlH6E9zBHca?dl=0

![img_0022](https://user-images.githubusercontent.com/914429/36546942-72833fb0-180e-11e8-8447-658ce4708578.jpg)
