### ISSUE TITLE
BeerJS #12: Bukowski Grill

### ISSUE THREAD

**Issue by partyordie** [beerjs/ekb#12]
21 March 2018
[Bukowski Grill](http://www.bukowski-grill.ru)
[Karla Libknekhta, 32](https://yandex.ru/maps/-/CBQ1ELcWKB)
8:00 p.m.

[Add to calendar](https://s3.amazonaws.com/partyordie/beerjs12.ics)

If you come, let us know by commenting the issue.

**Comment by partyordie** [comment]
🕶

**Comment by fortis** [comment]
✅

**Comment by evilj0e** [comment]
🙊

**Comment by antonlyaptsev** [comment]
🌴

**Comment by LeMarck** [comment]
:octocat:

**Comment by gibson** [comment]
👹

пн, 19 мар. 2018 г., 18:56 Петров Евгений <notifications@github.com>:

**Comment by Azomas** [comment]
:yum:

**Comment by monrus** [comment]
:beers:

**Comment by v3new** [comment]
☃️

**Comment by He4eT** [comment]
:octocat:

**Comment by evilj0e** [comment]
Ура! Вчера прошла 12 встреча BeerJS.

Обсудили подкаст Себранта, умный дом и как какой-то парень написал навык для Алисы, чтобы включала и выключала лампочку у него дома, про блокчейн в выборах, про чемпионат мира по футболу, про тайпскрипт и про выбор технологий, про то, что нужно обучать нейронки и на азиатах тоже, даже, если они не твои пользователи, про самый мощный ddos в истории и сервера Майнкрафта ♥️

Спасибо всем, кто пришёл. До встречи через 2 недели 💅

Оставляйте фидбек, проедложения по месту и темы тут: https://docs.google.com/forms/d/1nLHGUuTK4ZZmDoVIEmiN7DcTDJcMRIuxFrwfZOEBCgY

Ссылочки из общения:
• Подкаст Себранта: https://itunes.apple.com/ru/podcast/sebrant-chatting/id1320623324
• ОФД: https://ofd.yandex.ru
• ddos и майнкрафт: https://www.wired.com/story/mirai-botnet-minecraft-scam-brought-down-the-internet/
• «Активный гражданин» в Москве на блокчейне: https://github.com/moscow-technologies/ag-blockchain
• Навыки для Алисы: https://tech.yandex.ru/dialogs/alice/doc/about-docpage/

![img_1180](https://user-images.githubusercontent.com/914429/37785408-e19dd694-2e1b-11e8-864b-1f9141f975bd.JPG)

#summary
