### ISSUE TITLE
BeerJS #13

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#13]
4 April 2018
[«Воронеж»](https://vk.com/voronezhekb)
[Театральный переулок, 5А](https://yandex.ru/maps/-/CBqEi2bE-A)
8:00 p.m.

[Add to calendar](https://www.dropbox.com/s/aljt2uaityvaln6/BeerJS.ics?dl=1)

If you come, let us know by commenting the issue.

**Comment by Azomas** [comment]
:yum:

**Comment by antonlyaptsev** [comment]
🍒

**Comment by partyordie** [comment]
🍆

**Comment by gibson** [comment]
йа огурчик (лень эмоджи искать)

**Comment by evilj0e** [comment]
💅

**Comment by SoEasy** [comment]
🦐

**Comment by paulkotov** [comment]
участвую

**Comment by Iller45** [comment]
:heavy_plus_sign:

**Comment by drownbes** [comment]
👨

**Comment by vaseker** [comment]
два огурца!

**Comment by evilj0e** [comment]
Ура! Вчера прошла 13 встреча BeerJS.

Открытие вечера: в macos можно перемещать файлы по Cmd + Alt + V.

Обсудили тестирование скриншотами, normalizr, почему все кругом говорят про mobx, а используют redux, поспорили, где использовать кнопки, а где ссылки и прав ли в этом месте Мокеев, как получить моральный ущерб за снос телебашни, поговорили про Code Retreat и как придумать задания для него, про холакратию в Точке и FastDev и может ли она выродиться в охлократию, а ещё про mailru и коллекторов, Крав Магу, тюленей фаршированных чайками, селёдку, лакрицу и мармид ♥️

Спасибо всем, кто пришёл. Было интересно и весело. До следующего четверга – у нас внеплановая встреча перед DUMP 💅

Оставляйте фидбек, предложения по месту и темы тут: https://docs.google.com/forms/d/1nLHGUuTK4ZZmDoVIEmiN7DcTDJcMRIuxFrwfZOEBCgY
 

Ссылочки из общения:
• Пишет http реквесты для тестов, VCR: https://github.com/vcr/vcr
• Нормализует JSON: https://github.com/paularmstrong/normalizr
• Стейт менеджемент, про который говорят: https://github.com/mobxjs/mobx
• Стейт менеджемент, который используют: https://github.com/reactjs/redux
• Декларативный стейт менеджер со странным лого: https://github.com/cerebral/cerebral
• mailru и банки: https://www.rbc.ru/technology_and_media/02/04/2018/5abe534d9a7947350e3a7dfa
• Подкаст FrontendWeekend: https://soundcloud.com/frontend-weekend • Подкаст Code: https://codepodcast.com/ • Storybook: https://github.com/storybooks/storybook • React Cosmos: https://github.com/react-cosmos/react-cosmos • Редакс роутер без ерунды: https://github.com/auru/redux-unity-router
• Статья про Code Retreat: https://medium.com/@evilj0e/5facd3e044a6
• Крав Мага: https://www.youtube.com/watch?v=e9lUygdDUW4 
Фоточки: https://www.dropbox.com/sh/zl9ywojoad66a1v/AABIk2nTaXixIp67KF3b83N0a?dl=1

![img_3955](https://user-images.githubusercontent.com/914429/38364280-5ce38936-38f1-11e8-8a02-93078497a9f5.jpg)
