### ISSUE TITLE
BeerJS #16: Мята

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#16]
16 May 2018

[Мята](www.mintcafe.ru)
[Lenina str., 5L](https://yandex.ru/maps/-/CBUNF2FYHA)
8:00 p.m.

[Add to calendar](https://www.dropbox.com/s/aljt2uaityvaln6/BeerJS.ics?dl=1)

If you come, let us know by commenting the issue.

**Comment by evilj0e** [comment]
:icecream:

**Comment by SoEasy** [comment]
🚶‍♂️

**Comment by gibson** [comment]
🔮

**Comment by partyordie** [comment]
🏴

**Comment by LeMarck** [comment]
🚀

**Comment by ddddm** [comment]
🦁

**Comment by qisoft** [comment]
:beer:

**Comment by Azomas** [comment]
:yum:

**Comment by BolotskyDev** [comment]
:question:

**Comment by flafla** [comment]
🔢

**Comment by evilj0e** [comment]
Ура! В среду прошла 16 встреча BeerJS.

Особо ничего не записывал, так что саммари в это раз ультра короткое: радиоджс, фиксы, фэт байки, тапскрипт, саги, коллаборативный режим в вс код и атоме, «Тальков камень» и Делимобиль ♥️

Спасибо всем, кто пришёл. До встречи через две недели 💅

Оставляйте фидбек, предложения по месту и темы тут: https://docs.google.com/forms/d/1nLHGUuTK4ZZmDoVIEmiN7DcTDJcMRIuxFrwfZOEBCgY
 

Ссылочки из общения:
• Флобитс: https://github.com/Floobits/floobits-atom
• Лайв шэа для вс код: https://code.visualstudio.com/blogs/2017/11/15/live-share
• Телетайп для атом: https://teletype.atom.io
• Новый выпуск радиоджс: https://radiojs.ru/2018/05/выпуск-52-микросервисы-на-фронтенде/

![img_4078](https://user-images.githubusercontent.com/914429/40223515-c0881ad4-5a9c-11e8-81f6-237b7e7bc9c6.jpg)
