### ISSUE TITLE
BeerJS #19: Bar trip

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#19]
1 august 2018

We start at [бар Огонёк](https://yandex.ru/maps/-/CBucF6xPpB).
8:00 p.m.

If you come, let us know by commenting the issue.

**Comment by xeqlol** [comment]
🚀🚀🚀

**Comment by slogger** [comment]
🎛

**Comment by korniux** [comment]
👌

**Comment by flafla** [comment]
🤠

**Comment by partyordie** [comment]
🔥

**Comment by Azomas** [comment]
😋

**Comment by nulladdict** [comment]
⛩️

**Comment by Iller45** [comment]
:new_moon_with_face:

**Comment by SoEasy** [comment]
👨‍💻

**Comment by gibson** [comment]
тут мой эмодзи

**Comment by Shururup** [comment]
🦄

**Comment by sapfear** [comment]
🍣

**Comment by monrus** [comment]
:bear:

**Comment by dozor043** [comment]
👣

**Comment by libgtso** [comment]
:game_die:

**Comment by evilj0e** [comment]
![image 2018-08-02 12 44 24](https://user-images.githubusercontent.com/914429/43569736-cc55ef76-9651-11e8-96af-9259842b8978.jpg)

Альбом: https://yadi.sk/a/29pzjWpZ3ZpSbH
