### ISSUE TITLE
BeerJS #2: Grott Bar

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#2]
18 October 2017
[Grott Bar](https://grottbar.ru/)
[Lenina, 49](https://yandex.ru/maps/-/CBUXJPD50C)
8:00 p.m.

**Comment by evilj0e** [comment]
🐙

**Comment by evilj0e** [comment]
⚡️

**Comment by partyordie** [comment]
🖤

**Comment by Blackheart340** [comment]
:octocat:

**Comment by dontuse** [comment]
:beer:

**Comment by monrus** [comment]
🍺

**Comment by antonlyaptsev** [comment]
:octocat:

**Comment by Ivan-Feofanov** [comment]
:heavy_check_mark:

**Comment by denchistyakov** [comment]
👍

**Comment by evilj0e** [comment]
Хей хо! Начало традиции положено – вчера состоялся второй по счёту Бирджс ⚡️⚡️⚡️

В этот раз обсудили кучу всего технического, похэйтили Юру Дудя, узнали, что я практически “последний из могикан”, кто ставит `;` в js 🤦
Спасибо всем, кто пришёл.

Подписывайтесь на обновления репозитория, приглашайте друзей, вступайте в [Телеграм чат](https://t.me/beerjs_ekb) и всё такое. Увидимся через 2 недели. 🚀

Интересные ссылки, которые всплыли в разговоре:
* [Теорема зеро](https://www.kinopoisk.ru/film/teorema-zero-2013-696977/);
* [Она](https://www.kinopoisk.ru/film/ona-2013-577488/);
* [Видео про шрифт Папирус](https://www.youtube.com/watch?v=jVhlJNJopOQ);
* [Hacktoberfest](https://events.yandex.ru/events/meetings/21-october-2017/);
* [Подкаст Фронтенд Юность](https://soundcloud.com/frontend_u);
* [Подкаст Фронтенд Викенд](https://soundcloud.com/frontend-weekend);
* [Пули справедливости](https://youtu.be/wnERt9PVnAc);
* [Углеродный след в интернете](http://theruslan.ru/).

[Фоточки](https://photos.app.goo.gl/B8BgdqY9kcGSFZXe2).

![2017-10-19 11 15 55](https://user-images.githubusercontent.com/914429/31756730-e8f98c98-b4be-11e7-99ea-cb0127a7214f.jpg)
