### ISSUE TITLE
BeerJS #20: Fjord

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#20]
15 August 2018

[Fjord](https://www.instagram.com/fjordpub/)
[Pushkina, 7](https://yandex.ru/maps/-/CBuPETxbTA)
8:00 p.m.

If you come, let us know by commenting the issue.

**Comment by xeqlol** [comment]
🚀

**Comment by driventa** [comment]
🚠

**Comment by gibson** [comment]
🚠

**Comment by SoEasy** [comment]
🥩

**Comment by Azomas** [comment]
😋

**Comment by antonlyaptsev** [comment]
🕺

**Comment by Shururup** [comment]
🌚

**Comment by h3lpkey** [comment]
+1

**Comment by vaseker** [comment]
+2

**Comment by nulladdict** [comment]
🦀

**Comment by Na1ve** [comment]
🧀

**Comment by evilj0e** [comment]
![image 2018-08-17 01 16 47](https://user-images.githubusercontent.com/914429/44232680-3716d680-a1bb-11e8-8185-cc97bac832fb.jpg)
