### ISSUE TITLE
BeerJS #23: Нельсон Совин

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#23]
26 September 2018

[Нельсон Совин](http://nelsonsauvin.ru)
[Malysheva, 21/4](https://yandex.ru/maps/-/CBBR7CcV0C)
8:00 p.m.

If you come, let us know by commenting the issue.

**Comment by evilj0e** [comment]
Забронирован большой стол на втором этаже

**Comment by flafla** [comment]
🍻

**Comment by LeMarck** [comment]
:octocat:

**Comment by justerest** [comment]
+

**Comment by konstantinmit** [comment]
+

**Comment by Mello578** [comment]
+

**Comment by Iller45** [comment]
я не умею эмоджи )))

**Comment by partyordie** [comment]
![unadjustednonraw_thumb_af8](https://user-images.githubusercontent.com/2402615/46152396-5f015b80-c28a-11e8-94e0-e7caa536de0f.jpg)
