### ISSUE TITLE
BeerJS #25: На работе

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#26]
24 October 2018

[На работе](https://vk.com/narabotebar)
[Dekabristov street, 16/18B](https://yandex.ru/maps/-/CBBk6DdkGC)

8:00 p.m.

**Comment by evilj0e** [comment]
🍒

**Comment by SoEasy** [comment]
🐒

**Comment by He4eT** [comment]
🍑

**Comment by denchistyakov** [comment]
🔥

**Comment by proAlexandr** [comment]
👍

**Comment by LeMarck** [comment]
:octocat:

**Comment by Iller45** [comment]
:moyai:

**Comment by evilj0e** [comment]
![image 2018-10-25 11 15 11](https://user-images.githubusercontent.com/914429/47479673-41062700-d847-11e8-8efb-e96045dcd7de.jpg)
