### ISSUE TITLE
WineJS: Био Шмио

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#27]
31 October 2018

[Био Шмио](https://www.instagram.com/bioshmiobar)
[Malysheva street, 61](http://go.2gis.com/61owp)

8:00 p.m.

**Comment by evilj0e** [comment]
❔

**Comment by nulladdict** [comment]
🦀

**Comment by slogger** [comment]
👺

**Comment by ByMarsel** [comment]
🐌

**Comment by tenebricosa** [comment]
🍷

**Comment by kataev** [comment]
🤠

**Comment by LeMarck** [comment]
🚀

**Comment by vaseker** [comment]
+2️⃣

**Comment by Iller45** [comment]
:tanabata_tree:

**Comment by SoEasy** [comment]
😱

**Comment by gibson** [comment]
🎃

**Comment by Azomas** [comment]
😋

**Comment by igorlukanin** [comment]
🧠

**Comment by iAdramelk** [comment]
❓

**Comment by Lagoonnw** [comment]
:feet:

**Comment by vokakosh** [comment]
🐙

**Comment by DerArvend** [comment]
:musical_score:

**Comment by flafla** [comment]
👍

**Comment by evilj0e** [comment]
Спасибо всем за крутые костюмы, страшные истории и бурные обсуждения.

Нарушая традиции, сделали фоточку вовремя 📸

![image 2018-11-01 13 12 01](https://user-images.githubusercontent.com/914429/47840331-c9e90980-ddd7-11e8-9901-b9aed381871f.jpg)
