### ISSUE TITLE
BeerJS #26: Hopsinjoor

### ISSUE THREAD

**Issue by partyordie** [beerjs/ekb#28]
7 November 2018

[Hopsinjoor](https://www.instagram.com/hopsinjoorbar/)
[Belinskogo street, 30](https://yandex.ru/maps/-/CBBlqCrKSC)

8:00 p.m.

**Comment by flafla** [comment]
🎱

**Comment by LeMarck** [comment]
🎸

**Comment by vaseker** [comment]
🍑+🌶️

**Comment by Azomas** [comment]
😋

**Comment by iAdramelk** [comment]
👽

**Comment by evilj0e** [comment]
Кстати, спасибо всем, кто добрался до Хопсиньёра и что были терпеливы и дождались @partyordie (не то, что я) 😅
Обсудили диэлектрическую бумагу, прижки с гаражей, vim и vs code, BBQPitBoys, дни рождения и vuejs.

Хороших выходных. До встречи, через полторы недели.

![image 2018-11-09 18 19 01](https://user-images.githubusercontent.com/914429/48264625-fa6e1a80-e44b-11e8-9f28-9801f76a705b.jpg)
