### ISSUE TITLE
BeerJS #3: RatsKeller

### ISSUE THREAD

**Issue by partyordie** [beerjs/ekb#3]
1 November 2017
[RatsKeller](http://ratskeller.ru)
[8 Marta, 8B](https://yandex.ru/maps/-/CBaMYUX9HD)
8:00 p.m.

If you come, let us know by commenting the issue.

**Comment by partyordie** [comment]
🦄

**Comment by monrus** [comment]
🐥

**Comment by recound** [comment]
+1

**Comment by dontuse** [comment]
🍺

**Comment by iAdramelk** [comment]
🍺

**Comment by VoidArray** [comment]
🍺

**Comment by He4eT** [comment]
🐼

**Comment by partyordie** [comment]
@dontuse Лучиков здоровья, бро, приходи на следующий!

**Comment by flafla** [comment]
+

**Comment by evilj0e** [comment]
Отлично посидели!

Затёрли про завод трактора, путешествия и автостоп. Страной вечера оказалась, внезапно, Сербия. Спасибо всем, кто пришёл.

Ссылочки:
• Pebble (сайт лежит, хаха) https://en.wikipedia.org/wiki/Pebble_(watch)
• You are not so smart https://youarenotsosmart.com
• Xenogears https://en.wikipedia.org/wiki/Xenogears
• happypack https://github.com/amireh/happypack
• UglifyjsWebpackPlugin v1.0.0 https://webpack.js.org/plugins/uglifyjs-webpack-plugin/
• Клуб с тайским боксом в Екб http://thaifyn.ru
• Бритва Хэнлона https://ru.wikipedia.org/wiki/Бритва_Хэнлона
• Sony MDR-1000X https://www.sony.com/electronics/headband-headphones/mdr-1000x

![d18325fb-978f-4905-a89a-7330910d4841](https://user-images.githubusercontent.com/914429/32415218-19678a66-c247-11e7-9a6e-db90f695f0bb.jpeg)
