### ISSUE TITLE
BeerJS #34: Cannonball Brasserie

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#38]
10 April 2019

[Cannonball Brasserie](https://vk.com/cannonballekb)
[Karl Marks, 13](https://yandex.ru/maps/-/CCB2F2zq)

8:00 p.m.

**Comment by evilj0e** [comment]
🐝

**Comment by flafla** [comment]
👍

**Comment by LeMarck** [comment]
🚀

**Comment by gibson** [comment]
🙃

**Comment by tooshort** [comment]
🍵

**Comment by molokovev** [comment]
💣

**Comment by Azomas** [comment]
:yum:

**Comment by konstantinmit** [comment]
1

**Comment by klikkn** [comment]
+

**Comment by DenisAntonov33** [comment]
+1

**Comment by evilj0e** [comment]
Всем спасибо, что пришли и решали смешные задачки на логику.

Вчера обсудили буткемп в Яндексе, посплетничали почему @kataeva бросила UralJS и он умер, порассуждали как влияет месторасположение "Контура" на людей, которые там работают, про HolyJS, поспорили нужны ли деньги в лесу и сколько стоит бревно, а ещё как всё взвесить.

![IMAGE 2019-04-12 09:49:26](https://user-images.githubusercontent.com/914429/56013006-53e2ba00-5d08-11e9-8463-c5d8153ef2ba.jpg)
