### ISSUE TITLE
BeerJS #35: Shrmps + Brgrs

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#39]
18 April 2019

[Shrmps + Brgrs](https://www.instagram.com/shrmps_brgrs/)
[Malysheva, 24](https://yandex.ru/maps/-/CBq4fGbELA)
8:00 p.m.

If you come, let us know by commenting the issue.

**Comment by konstantinmit** [comment]
+

**Comment by xeqlol** [comment]
:trollface:

**Comment by lekzd** [comment]
🎸

**Comment by flafla** [comment]
🚶

**Comment by SoEasy** [comment]
🦐

**Comment by Vadim-Moshev** [comment]
Let's find out what beer.js is

**Comment by tenebricosa** [comment]
🐝

**Comment by Vadim-Moshev** [comment]
У меня вопрос. Как можно будет на месте обозначиться? Типа, я пришёл на beer.js, а не случайны посетитель?

**Comment by evilj0e** [comment]
@Vadim-Moshev, увидишь много людей – это мы. Если хочется точно удостовериться и найтись, то пиши в https://t.me/beerjs_ekb

**Comment by LeMarck** [comment]
:roket:

**Comment by molokovev** [comment]
🦐

**Comment by ByMarsel** [comment]
:godmode:

**Comment by dozor043** [comment]
🍔 🍻

**Comment by gibson** [comment]
🤪

**Comment by mairiv** [comment]
🎏

**Comment by evilj0e** [comment]
Спасибо всем, кто пришел. Надеюсь, вы хорошо пообщались и обсудили доклады с Dump и подготовили свой перечень фаворитов.

![IMAGE 2019-04-22 11:52:47](https://user-images.githubusercontent.com/914429/56487607-28748200-64f5-11e9-8640-c630f7ca87bb.jpg)
