### ISSUE TITLE
BeerJS coding #2: Комбинат

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#40]
24 April 2019

[Комбинат](http://combinat.work)
[8th March, 32A](https://yandex.ru/maps/-/CBFGBAS18C)

Notebook, ~200₽

7:00 p.m.

**Comment by evilj0e** [comment]
💻

**Comment by LeMarck** [comment]
:rocket:

**Comment by xeqlol** [comment]
:trollface: 


_меня заставили_

**Comment by xiiivii** [comment]
🚫

**Comment by flafla** [comment]
🙈

**Comment by SoEasy** [comment]
🦇

**Comment by klikkn** [comment]
:tractor:

**Comment by DenisAntonov33** [comment]
👨‍💻

**Comment by Vadim-Moshev** [comment]
NaN, undifined, null

**Comment by evilj0e** [comment]
Спасибо всем, кто пришёл. Повторили как складывать два числа, а ещё как определить, что массив чисел почти монотонно возрастающий 🙂 Нарешались вдоволь.

![IMAGE 2019-04-25 10:04:53](https://user-images.githubusercontent.com/914429/56710873-93b29400-6741-11e9-8221-72859014a1e2.jpg)
