### ISSUE TITLE
BeerJS #37: Red ace

### ISSUE THREAD

**Issue by Vadim-Moshev** [beerjs/ekb#43]
5 June 2019

[Бар «RED ACE»](https://vk.com/redacebar)
[Sacco & Vanzetti street, 48](https://2gis.ru/ekaterinburg/query/%D1%81%D0%B0%D0%BA%D0%BA%D0%BE%20%D0%B8%20%D0%B2%D0%B0%D0%BD%D1%86%D0%B5%D1%82%D1%82%D0%B8%2C%2048/geo/1267273050366690?queryState=center%2F60.588106%2C56.835817%2Fzoom%2F16)
8:00PM (20:00)

If you'll come let us know by commenting this issue

**Comment by gibson** [comment]
🤟🏿

**Comment by Na1ve** [comment]
🍺

**Comment by Vadim-Moshev** [comment]
Встреча завершилась. Пришло 6 человек. Ожидаем фотки.
Затронутые темы:
1. я сказал, что неприятно было читать, что ES6 классы — это синтаксический сахар над prototype, но, к сожалению, так оно и есть;
2. как можно получить люлей от линта и от typeScript, если последнему подсунуть код на ванильном JS;
3. я рассказывал, что такое JScript (немного);
4. краем уха услышал, что setState в React лучше хуков;
5. Angular предназначен лишь для прототипирования, для продакшна он не подходит (тоже услышал);
6. обсудили big int.

______

Хорошие хот-доги, вкусное пиво. Порадовало почти полное отсутствие музыки, не пришлось перекрикивать.

**Comment by gibson** [comment]
![20190605_211639](https://user-images.githubusercontent.com/140022/59003123-23ae2800-882e-11e9-8193-df27a9949080.jpg)

**Comment by gibson** [comment]
![im](https://user-images.githubusercontent.com/140022/59003223-7ee01a80-882e-11e9-8b51-6371abf8bd27.jpg)
