### ISSUE TITLE
BeerJS #40: Агонь

### ISSUE THREAD

**Issue by Vadim-Moshev** [beerjs/ekb#46]
17 July 2019

[Агонь](https://www.the-village.ru/village/food/place/346437-restoran-na-meste-ratsa)
[8th March street, 8Б](https://2gis.ru/ekaterinburg/query/8%20%D0%BC%D0%B0%D1%80%D1%82%D0%B0%208%D0%91/geo/1267273050366145?queryState=center%2F60.601938%2C56.836268%2Fzoom%2F16)
8:00PM

If you come, let us know by commenting the issue.

P. S. Если до утра среды никто не отметится, я буду вынужден отменить бронь. Не хочу снова быть один (то есть, приходить впустую).

**Comment by Vadim-Moshev** [comment]
undefined

**Comment by zhurunovrodion** [comment]
буду

**Comment by sapfear** [comment]
:bullettrain_side:

**Comment by SNPR** [comment]
🛴

**Comment by Vadim-Moshev** [comment]
Встреча завершена. Спасибо всем, кто пришёл.

Фотография
![photo_2019-07-18_02-14-56](https://user-images.githubusercontent.com/39858114/61412525-881ad780-a902-11e9-8c7a-59525222bab8.jpg)
