### ISSUE TITLE
BeerJS #41: Bar trip

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#48]
1 august 2019

We start at [Lamadjo](https://yandex.ru/maps/-/CGUZR45N).
8:00 p.m.

If you come, let us know by commenting the issue.

**Comment by Iller45** [comment]
+

**Comment by Vadim-Moshev** [comment]
undefined

**Comment by nulladdict** [comment]
🦀

**Comment by He4eT** [comment]
🍼

**Comment by slogger** [comment]
⚰️

**Comment by partyordie** [comment]
🖤

**Comment by evilj0e** [comment]
🦀

**Comment by LeMarck** [comment]
🚀

**Comment by gibson** [comment]
🚀💵

**Comment by zhurunovrodion** [comment]
i am too

**Comment by molokovev** [comment]
🧗

**Comment by paulkotov** [comment]
:hamburger:

**Comment by serjo96** [comment]
{\__/}
(●_●)
( >🌮

**Comment by proAlexandr** [comment]
🍻

**Comment by Na1ve** [comment]
:beer: +1

**Comment by partyordie** [comment]
![IMG_3094](https://user-images.githubusercontent.com/2402615/62533569-6c02ba00-b860-11e9-91f0-bf8a4a2d8963.jpeg)

Так, дайте вспомнить.

Встретились в **Ламаджо** — собрались, поужинали.
_Взял бургер и пинту нефильтрованного. Сносно._

Сытые и довольные двинули в **Синдром**. Послушали хуёвых стендапов, понедоумевали.
_Купил КРЫЖОВНИКОВЫЙ МИЛКШЕЙК ЭЛЬ, ничёси. Не попробовал его, потому что потерял где-то._

Дальше отправились в **Ню бар**. Там хорошо, как обычно.
_Белый русский, ок._

Потом — в **Коллектив**. Пришли в изумление от коктейлей из меню-карточки.
_Джиново-базиликовое нечто на глыбе льда. Язык проглотил, глаза на лоб, челюсть отвалилась._

Ворвались в **Нельсон Совин** прямо перед закрытием. Тридцать тысяч сортов пиваса. Все попробовали.
_Выбрал какую-то ипу наугад. Выпить не осилил, слабак._

Закончили тусэ в **Телевизоре**. Поиграли в кикер, я всех выиграл.
_Мягкий грушевый сидр. Вкусно._

Спасибо всем, кто пришёл. С вами было хорошо.
Спасибо Роме за отличный повод собраться.
Спасибо Антону и Олегу за маршрут и организацию.

🖤

**Comment by tooshort** [comment]
❤️

**Comment by eshulyndina** [comment]
❤️
