### ISSUE TITLE
BeerJS #5: Brittania

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#5]
29 November 2017
[Brittania](http://www.britannia-pub.ru/)
[Vainera, 64A](https://yandex.ru/maps/-/CBaZRJqEDB)
8:00 p.m.

[Add to calendar](https://s3.amazonaws.com/partyordie/beerjs5.ics)

If you come, let us know by commenting the issue.

**Comment by partyordie** [comment]
💋

**Comment by antonlyaptsev** [comment]
:tada:

**Comment by evilj0e** [comment]
:+1:

**Comment by monamonax** [comment]
😎

**Comment by sashasushko** [comment]
🍺

**Comment by KORN1UX** [comment]
🧐

**Comment by tenebricosa** [comment]
🔥

**Comment by SoEasy** [comment]
🚀

**Comment by He4eT** [comment]
💊

**Comment by flafla** [comment]
🍺

**Comment by sashasushko** [comment]
Вчера обсуждали ссылки. В том числе сайт чувака, который много и интересно пишет про JS. Вроде, это был тот, о ком я подумал, но на всякий случай закидываю свою ссылку - http://dmitrysoshnikov.com

**Comment by partyordie** [comment]
Отлично! Мы вот-вот запилим итоги.

**Comment by evilj0e** [comment]
Е! Прикольно вчера затёрли за технологии, GraphQL, Angular, рабство Гугла и виндовую тему в атоме, тестирование и взяли крутое интервью у живого разработчика из Сима-Ленд.

Спасибо всем, кто пришёл.
До встречи оффлайн через 2 недели.

Ссылочки из шоунотов:
* Redux v4: https://github.com/reactjs/redux/releases/tag/v4.0.0-beta.1
* Скорость и Дэн Абрамов: https://github.com/reactjs/redux/pull/2599
* Курс от роутер-чуваков: https://reacttraining.com/patterns/
* Конспекты Сошникова по Джс: http://dmitrysoshnikov.com
* Доклад про овер-инжениринг: https://www.youtube.com/watch?v=GRr4xeMn1uU
* Force HTTPS: https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/
* Убер крутая тема для Атома: https://atom.io/themes/aesthetic-ui
* Курс Кайла Симсона бесплатно до 4 декабря: https://frontendmasters.com/teachers/kyle-simpson/
* В Реакте появились фрагменты: https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html

Ссылочки из общения:
• Битовые карты: https://ru.wikipedia.org/wiki/Битовая_карта
• Колаборативная разработка в Атоме: https://github.com/blog/2468-introducing-teletype-for-atom-code-collaboratively-in-real-time
• Лайв шэа в ВСКод: https://code.visualstudio.com/blogs/2017/11/15/live-share
• Тестирование с Джест: http://facebook.github.io/jest/

![2017-11-30 16 20 20](https://user-images.githubusercontent.com/914429/33428382-616b1c18-d5ea-11e7-81b9-0590a8bf1605.jpg)

p.s.: Мы вот немного лажанули и забыли сфоткаться, пока все были 🙁 В следующий раз реабилитируемся.
