### ISSUE TITLE
BeerJS #43: Коллектив

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#50]
29 August 2019
[Коллектив](https://www.instagram.com/klktv91/)
[8 March street, building 8g](https://go.2gis.com/1kq2p)

8:00PM

If you come, let us know by commenting the issue.

**Comment by evilj0e** [comment]
💀

**Comment by Na1ve** [comment]
🐱

**Comment by nulladdict** [comment]
(ᵔᴥᵔ)

**Comment by rustho** [comment]
🍨

**Comment by flafla** [comment]
🙈

**Comment by Iller45** [comment]
+

**Comment by Vadim-Moshev** [comment]
NaN

**Comment by LeMarck** [comment]
🚀

**Comment by SNPR** [comment]
:shallow_pan_of_food:

**Comment by evilj0e** [comment]
Вчера прошла 43 встреча.

Всем спасибо, что пришли. Мне было приятно с вами пообщаться. Обсудили реакт, редакс, кодварс, курсы по джаваскрипту, стартапы, группу «кис-кис» и «убийц», посмотрели на забомбленный минивен, а ещё зачем нужны Мап и Сэт, если есть объекты и массивы.

До скорого ✨

![IMAGE 2019-08-30 17:37:31](https://user-images.githubusercontent.com/914429/64021202-d8659600-cb4c-11e9-8d2d-84efb1c1510d.jpg)

**Comment by Vadim-Moshev** [comment]

