### ISSUE TITLE
BeerJS #45: Стрелка

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#52]
3 October 2019
[Стрелка](https://m.vk.com/strelka_kraft_bar)
[8 March street, 18](
https://go.2gis.com/wlmjg)

8:00PM

If you come, let us know by commenting the issue.

**Comment by evilj0e** [comment]
💃🏻

**Comment by gibson** [comment]
🤖

**Comment by LeMarck** [comment]
🚀

**Comment by flafla** [comment]
🚶

**Comment by Iller45** [comment]
🏄

**Comment by xeqlol** [comment]
🚀

**Comment by He4eT** [comment]
🧯

**Comment by Vadim-Moshev** [comment]
NaN

**Comment by sergeialimov** [comment]
:beer:

**Comment by tenebricosa** [comment]
🦕

**Comment by Aminopyridin** [comment]
🐯

**Comment by Alehandro231** [comment]
💃🏻

**Comment by Ti-webdev** [comment]
:beers:

**Comment by cale148** [comment]
:tropical_drink:

**Comment by vsevolodroschupkin** [comment]
🐱‍🏍

**Comment by partyordie** [comment]
😀

**Comment by username40** [comment]
👍  🍺

**Comment by SoEasy** [comment]
👴🏿

**Comment by rustho** [comment]
🐱‍👓

**Comment by Azomas** [comment]
:yum:

**Comment by kostyaBro** [comment]
Мб приду

**Comment by evilj0e** [comment]
Спасибо всем кто вчера пришёл, а ещё тем, кто вернулся в чатик ☺️

Оккупировали «Стрелку». Обсуждали вебпекмано, стайлманов, всякие курсы, зарплаты, эджайл в жизни, помидорки и много чего ещё.

До встречи

![IMAGE 2019-10-04 15:29:15](https://user-images.githubusercontent.com/914429/66201013-ba470480-e6bb-11e9-8027-e08fb52c8fe0.jpg)

**Comment by Vadim-Moshev** [comment]
На самом деле на встрече были сделаны ещё фото, но это было уже после того, как бОльшая часть ушла. Фотографии предоставлены Валерием Трушковым (flafla), за что ему спасибо.

Девушка на фотографии — это бармен этого бара, Варвара.

![photo_2019-10-10_00-29-46](https://user-images.githubusercontent.com/39858114/66514700-1fa15800-eaf7-11e9-9cdb-76340ead24bc.jpg)
![photo_2019-10-10_00-29-50](https://user-images.githubusercontent.com/39858114/66514701-2039ee80-eaf7-11e9-9027-551bac8e8947.jpg)
![photo_2019-10-10_00-29-51](https://user-images.githubusercontent.com/39858114/66514704-2039ee80-eaf7-11e9-931b-ee48469b1483.jpg)
