### ISSUE TITLE
BeerJS #47: Твой бар

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#59]
6 November 2019
[Твой бар](https://www.instagram.com/barvekb/)
[Vaynera, 70](https://go.2gis.com/a2ill)

8:00 p.m.

If you come, let us know by commenting the issue.

**Comment by gibson** [comment]
🤟🏿

**Comment by dolgihnatasha** [comment]
🍏

**Comment by Vadim-Moshev** [comment]
...

**Comment by zhurunovrodion** [comment]
Приду

**Comment by Vadim-Moshev** [comment]
Фотография от Ивана
![photo_2019-11-07_23-10-36](https://user-images.githubusercontent.com/39858114/68415312-e589ab80-01b3-11ea-9d0f-8f814871e020.jpg)
