### ISSUE TITLE
BeerJS #49 50 Костей

### ISSUE THREAD

**Issue by NikitaDerevskov** [beerjs/ekb#62]
23 January 2020.

Place: 
[50 Костей](http://50bones.ru/)
[8 March, 23В](https://go.2gis.com/iuq0r)

Start: 20:00

If you come, let us know by commenting on the issue.

**Comment by BolotskyDev** [comment]
🐐

**Comment by xeqlol** [comment]
🚀

**Comment by LeMarck** [comment]
:octocat:

**Comment by NikitaDerevskov** [comment]
:checkered_flag:

**Comment by gibson** [comment]
🔥🦄

**Comment by KreveDKO** [comment]
🍷

**Comment by SoEasy** [comment]
🐠

**Comment by Vadim-Moshev** [comment]
Встреча завершена. Вот фотография
![imgonline-com-ua-Mirror-ZCbHIKgqi3](https://user-images.githubusercontent.com/39858114/73024239-02e32300-3e4f-11ea-8505-89f2c1791bc6.jpg)
