### ISSUE TITLE
BeerJS #50 Pan Smetan

### ISSUE THREAD

**Issue by Vadim-Moshev** [beerjs/ekb#64]
19 February 2020 (Wednesday)

[Пан Сметан](https://pansmetan.ru/)
[Vostochnaya Street, 82](https://2gis.ru/ekaterinburg/search/%D0%B2%D0%BE%D1%81%D1%82%D0%BE%D1%87%D0%BD%D0%B0%D1%8F%2082/geo/1267273050363906/60.633932%2C56.834288/tab/inside?m=60.634587%2C56.834193%2F18.08)

Start: 20:00

If you come, let us know by commenting on the issue.

Примечание: по средам скидки 50% на всё разливное пиво
Note: there is 50% off for all kinds of bear on each Wendesday

**Comment by BolotskyDev** [comment]
:hurtrealbad:

**Comment by xeqlol** [comment]
:rocket:

**Comment by Vadim-Moshev** [comment]
Встреча завершена. Фотографии участников
![photo_2020-02-20_16-54-58](https://user-images.githubusercontent.com/39858114/74932089-d21cec00-5402-11ea-973c-99470e27460d.jpg)
![photo_2020-02-20_16-55-00](https://user-images.githubusercontent.com/39858114/74932100-d517dc80-5402-11ea-9aaa-98a69d352b6c.jpg)
![photo_2020-02-20_16-55-04](https://user-images.githubusercontent.com/39858114/74932101-d5b07300-5402-11ea-863d-f8c87a2e686e.jpg)
![photo_2020-02-20_16-55-07](https://user-images.githubusercontent.com/39858114/74932102-d5b07300-5402-11ea-8cff-e93e120a3ed5.jpg)
