### ISSUE TITLE
BeerJS #51: Твой бар

### ISSUE THREAD

**Issue by Vadim-Moshev** [beerjs/ekb#66]
5 March 2020
[Твой бар](https://www.instagram.com/barvekb/)
[Vaynera, 70](https://go.2gis.com/a2ill)
8:00 p.m.

If you come, let us know by commenting the issue.

**Внимание. В баре действуют ограничения, заключающиеся в том, что мы сможем занять забронированный столик не более, чем на три часа. Ограничения введены ввиду популярности заведения. Говорят, трёх часов вполне хватит, чтобы отдохнуть и насладиться атмосферой.**

**Comment by Na1ve** [comment]
👌

**Comment by Vadim-Moshev** [comment]
Нас было трое: к нам присоединился ещё Саша Snake. Выкладываю фотографии. Одна из них — это фотография робобара.

![1](https://user-images.githubusercontent.com/39858114/76160863-95195f00-614f-11ea-8fd3-064855aaa304.jpg)
![2](https://user-images.githubusercontent.com/39858114/76160864-964a8c00-614f-11ea-8779-227bb60c5673.jpg)
![3](https://user-images.githubusercontent.com/39858114/76160865-96e32280-614f-11ea-9e51-9ceca1b7fc83.jpg)
