### ISSUE TITLE
BeerJS #53: Bar trip 

### ISSUE THREAD

**Issue by rustho** [beerjs/ekb#69]
10 september 2k2d

We start at [Shrimps & Burgers](https://yandex.ru/maps/-/CCQxM4bjwC).
8:00 p.m.

If you come, let us know by commenting the issue.

**Comment by KreveDKO** [comment]
🍷

**Comment by BolotskyDev** [comment]
🍻

**Comment by Na1ve** [comment]
🍺

**Comment by mainframev** [comment]
🍻
