### ISSUE TITLE
BeerJS #7: Мой друг Оливье

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#7]
10 January 2018
[Мой друг Оливье](https://www.myfriendolivier.ru)
[Bank lane, 10](https://yandex.ru/maps/-/CBal5TEXDD)
8:00 p.m.

[Add to calendar](https://www.dropbox.com/s/n52obrtbjwfuxm3/BeerJS-7-My-Friend-Olivier.ics?dl=1)

If you come, let us know by commenting the issue.

**Comment by evilj0e** [comment]
🍍

**Comment by Vestrond** [comment]
🧀

**Comment by LeMarck** [comment]
🚀

**Comment by Ivan-Feofanov** [comment]
:tea:

**Comment by SoEasy** [comment]
🕉

**Comment by sirius-ryuga** [comment]
:dragon_face:

**Comment by TimeRaider** [comment]
🏄

**Comment by steppefox** [comment]
🇰🇿

**Comment by Azomas** [comment]
:octocat:

**Comment by margaritashvetsov** [comment]
🎈

**Comment by partyordie** [comment]
❄️

**Comment by antonlyaptsev** [comment]
:octocat:

**Comment by Golubkov-P** [comment]
👍

**Comment by iAdramelk** [comment]
👽

**Comment by gentlepudding** [comment]
:dancer:

**Comment by Dunwolf** [comment]
:+1:

**Comment by sashasushko** [comment]
🍔

**Comment by evilj0e** [comment]
Поздравляю всех с Бирджс Екатеринбург #7 и #1 в этом году. 
Вчера нас впервые собралось 20 человек.
Ура!

Покушали Оливье в честь прошедшего Нового года и приближающегося Старого Нового года. Прикольно пообщались про Австралию и сёрфинг, про Атлассиан, про космос для реакта, про фантастику, Японию и Ситника, про то, как лучше подходить к мобайл фёст вёрстке.

Спасибо всем, кто пришёл. 🔥

Ссылочки из общения:
• Атлассиан: atlassian.com
• Джира: atlassian.com/software/jira
• Реакт Космос: react-cosmos.github.io
• Драг-н-дроп: github.com/atlassian/react-beautiful-dnd
• Курс от роутер-чуваков: reacttraining.com/patterns/

Фоточки: https://www.dropbox.com/sh/nv7avctopn8tjus/AABCCao7HZvz0gTCdl-d3K7Da?dl=0

![img_1071](https://user-images.githubusercontent.com/914429/34811912-34c360ac-f6c5-11e7-9abe-cff6ae254e47.JPG)
