### ISSUE TITLE
BeerJS #54: Самоцвет

### ISSUE THREAD

**Issue by rustho** [beerjs/ekb#71]
29 October 2020, Thursday

Самоцвет
[Малышева, 29а](https://go.2gis.com/ro0bo) 

8:00 p.m.

If you'll come let us know by commenting this issue

**Comment by Aminopyridin** [comment]
🐅

**Comment by KreveDKO** [comment]
🍷

**Comment by zhurunovrodion** [comment]
+

**Comment by SoEasy** [comment]
🇪🇪

**Comment by Razdva122** [comment]
:space_invader:

**Comment by serjo96** [comment]
+

**Comment by qisoft** [comment]
💻 📡

**Comment by rustho** [comment]
Отлично покутили до 23:00. Пробовали дистиляты, общались за эстонскую релокацию, квартиры с саунами, странные собесы и деконструкцию

![image](https://user-images.githubusercontent.com/26579566/97696564-92e18780-1ac7-11eb-91ab-69e9ce1abbd8.jpeg)

**Comment by evilj0e** [comment]
@rustho добавь в ридми ещё, плиз
