### ISSUE TITLE
BeerJS #55: бар Стрелка

### ISSUE THREAD

**Issue by SoEasy** [beerjs/ekb#73]
24 Декабря 2020, четверг

Бар Стрелка, ул. 8 Марта, 18, вход с 8 марта в арку, в конец двора, там налево.

20:00 по Екб

Ставьте картиночку, если придете :)

Я присутствовать не смогу, но желающие - велком )
Как приеду в Екб - еще одну встречу организую

**Comment by flafla** [comment]
🤠

**Comment by Na1ve** [comment]
🍻

**Comment by Iller45** [comment]
🧤

**Comment by Aminopyridin** [comment]
🦀

**Comment by mainframev** [comment]
🍺

**Comment by KreveDKO** [comment]
🍷

**Comment by GitSerg** [comment]
:confetti_ball:

**Comment by BolotskyDev** [comment]
🚀

**Comment by dozor043** [comment]
🍻
