### ISSUE TITLE
BeerJS #56: Географ

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#74]
20 February 2021, Saturday

[Географ](https://go.2gis.com/sm0v1) 
[Kuybisheva, 61](https://go.2gis.com/beytn) 

8:00 p.m.

If you'll come let us know by commenting this issue

**Comment by evilj0e** [comment]
✈️

**Comment by flafla** [comment]
🤠

**Comment by rustho** [comment]
🐈

**Comment by He4eT** [comment]
:balloon:

**Comment by serjo96** [comment]
🥃🌚

**Comment by mishenkoa** [comment]
💩

**Comment by xeqlol** [comment]
👍

**Comment by Lagoonnw** [comment]
&#129437;

**Comment by Iller45** [comment]
🤺

**Comment by JuliaOgorodnova** [comment]
🐥

**Comment by rrayd** [comment]
🕵️‍♂️

**Comment by Na1ve** [comment]
🍻

**Comment by rustho** [comment]
![IMG_6735_Original](https://user-images.githubusercontent.com/26579566/126312753-42c1bd29-325a-461a-ab6a-60514fe6a6e3.jpg)
@evilj0e may be close?
