### ISSUE TITLE
BeerJS #58: Нельсон Совин бар

### ISSUE THREAD

**Issue by NoLogicTheOne** [beerjs/ekb#76]
17.06.2022, пятница

Нельсон Совин бар
[ул. Малышева, 21/4](https://yandex.ru/profile/1795519767?no-distribution=1&source=wizbiz_new_map_single)

8:00 p.m.

If you'll come let us know by commenting this issue

**Comment by monrus** [comment]
:beer:

**Comment by Lagoonnw** [comment]
:cocktail:

**Comment by SoEasy** [comment]
🧐

**Comment by JuliaOgorodnova** [comment]
🥂

**Comment by IgorSushko1** [comment]
🥂

**Comment by monrus** [comment]
+

**Comment by Na1ve** [comment]
🍺

**Comment by Na1ve** [comment]
🍺

**Comment by kominov** [comment]
🍺
