### ISSUE TITLE
BeerJS #61: Мой Бар

### ISSUE THREAD

**Issue by sokolovstas** [beerjs/ekb#79]
11 ноября 20:00

Мой Бар
[ул. Вильгельма де Геннина, 47] (https://2gis.ru/ekaterinburg/geo/70000001025997901)

Если вы хотите прийти, то оставьте любой комментарий к задаче

**Comment by NoLogicTheOne** [comment]
I will be there =) +1 mb =)

**Comment by Na1ve** [comment]
🍺

**Comment by evilj0e** [comment]
@sokolovstas привет! закрой шью, пожалуйста, и обнови ридми

**Comment by sokolovstas** [comment]
@evilj0e спасибо!
