### ISSUE TITLE
BeerJS #8: Gordon's Doctor Scotch Pub

### ISSUE THREAD

**Issue by partyordie** [beerjs/ekb#8]
24 January 2018
[Gordon's Doctor Scotch Pub](http://www.doctorscotch.ru/doctor/)
[Malysheva, 56A](https://yandex.ru/maps/-/CBeYUWqPOA)
8:00 p.m.

[Add to calendar](https://s3.amazonaws.com/partyordie/beerjs8.ics)

If you come, let us know by commenting the issue.

**Comment by partyordie** [comment]
🍆

**Comment by evilj0e** [comment]
🌴

**Comment by monrus** [comment]
:beers:

**Comment by antonlyaptsev** [comment]
:tada:

**Comment by ByMarsel** [comment]
💩

**Comment by xeqlol** [comment]
⚛️

**Comment by Azomas** [comment]
:metal:

**Comment by korniux** [comment]
🙏

**Comment by xiiivii** [comment]
🇷🇸

**Comment by mshatikhin** [comment]
🏋️

**Comment by nulladdict** [comment]
👨‍👨‍👦‍👦

**Comment by sashasushko** [comment]
🍹

**Comment by tenebricosa** [comment]
🖖🏾

**Comment by kataev** [comment]
😬

**Comment by flafla** [comment]
🤠

**Comment by LeMarck** [comment]
🚀

**Comment by slogger** [comment]
🔢

**Comment by evilj0e** [comment]
Ае! Вчера прошла 8 встреча BeerJS.

Было супер много тем. Поболтали про Смерть Сталина и Ройзмана, про клоджуре, акцент Дэна Абрамова, Фортрана из мультика, преакт и его тысячи звёзд, а ещё про то, что метро в Екб вообще не нужно.

Спасибо всем, кто пришёл. До встречи через 2 недели. 💅

Ссылочки из общения:
• Возможно смешная комедия «Мы – легенды / Двое в пустом Париже»: kinopoisk.ru/film/my-legendy-2008-391367/ 
• Ройзман у Дудя: youtube.com/watch?v=S9y4R11gzPY
• Матильда: youtube.com/watch?v=S9y4R11gzPY
• Смерть Сталина: www.kinopoisk.ru/film/smert-stalina-2017-972919/
• Язык программирования для гопников и норм поцыков: yopta.space
• Мемоайз в лодеш только по первому аргументу: github.com/lodash/lodash/issues/3607
• Клоджуре и кложаскрипт: clojure.org, clojurescript.org
• Энциклопедия Фортрана: ru.wikipedia.org/wiki/Энциклопедия_профессора_Фортрана
• Аполло-сервер: github.com/apollographql/apollo-server
• Доклад Абрамова с акцентом: www.youtube.com/watch?v=xsSnOQynTHs
• Преакт: github.com/developit/preact

Ссылочки из шоунотов:
• Эксклюзивная логистика: artlebedev.ru/exclusive-logistics/
• Деревня для разработчиков: vc.ru/32055-byvshiy-sotrudnik-yandeksa-potratil-11-mln-rubley-i-sozdal-poselok-dlya-programmistov-v-kirovskoy-oblasti
• Фриланс и Дэн Абрамов: www.fl.ru/users/gaearon/opinions/

#summary
![2018-01-25 11 51 18](https://user-images.githubusercontent.com/914429/35374759-16b40a74-01c6-11e8-9a21-657865153129.jpg)
