### ISSUE TITLE
BeerJS #9: Beirhof

### ISSUE THREAD

**Issue by evilj0e** [beerjs/ekb#9]
7 February 2018
[Bierhof](http://bierhof.bar)
[Radischeva, 25](https://yandex.ru/maps/-/CBeBV8FhHD)
8:00 p.m.

[Add to calendar](https://www.dropbox.com/s/f7imtqck9gorypn/BeerJS-9-Bierhof.ics?dl=1)

If you come, let us know by commenting the issue.

**Comment by evilj0e** [comment]
🏴

**Comment by sirius-ryuga** [comment]
🐲

**Comment by nulladdict** [comment]
🦀

**Comment by monrus** [comment]
:beer:

**Comment by SoEasy** [comment]
🍖

**Comment by miracle-sun** [comment]
🦄

**Comment by nanot1m** [comment]
⍢

**Comment by xeqlol** [comment]
🌴

**Comment by partyordie** [comment]
🍄

**Comment by mshatikhin** [comment]
🍻

**Comment by tenebricosa** [comment]
❓

**Comment by slogger** [comment]
🏓

**Comment by antonlyaptsev** [comment]
:octopus:

**Comment by sameoldmadness** [comment]
🍆

**Comment by Aminopyridin** [comment]
🎱

**Comment by gentlepudding** [comment]
:octocat:

**Comment by maxvipon** [comment]
🐨

**Comment by eshulyndina** [comment]
🔥💣

**Comment by LeMarck** [comment]
🚀

**Comment by nishirken** [comment]
🚀

**Comment by evilj0e** [comment]
Ае! Прошла 9 встреча BeerJS.

Было куча спорных тем про культуру работы: нужно ли отвечать с фидбеком на письма рекрутеров; почему очень сложно попасть в IT, если тебе, например, 55, у тебя есть громадный опыт за плечами, но не в IT; является ли зарплата единственным критерием выбора вакансии.

Ребята поделились информацией о ближайших событиях в it, @mshatikhin приглашает в поход на «Конжаковский камень».

@eshulyndina, @Razrushana спасибо за то, что пришли и болтали с нами на каверзные темы. 

Спасибо всем, кто пришёл. До встречи через 2 недели. 💅

Ссылочки из общения:
• [Пост](https://mshatikhin.wordpress.com/2015/02/20/survive/) @mshatikhin про прошлый поход
• [Яндекс и Просвещение](https://education.yandex.ru)
• В этой книге есть [результаты исследования влияния гаджетов на мозг](https://www.alpinabook.ru/catalog/BooksForParents/84651/)
• [Результаты исследования состояния фронтенда. В среднем отставание библиотек от лэйтест версий 1177 дней, так что у вас проект не легаси](http://www.ccs.neu.edu/home/arshad/publications/ndss2017jslibs.pdf)

События:
• 10.02: [Лекция Брюса Момжиана про PostgreSQL](https://www.it-people.ru/brucemomjian-in-ekaterinburg)
• 16.02: [iOS Code Nights, VR/AR](https://events.yandex.ru/events/meetings/16-february-2018/)

[Фоточки](https://www.dropbox.com/sh/kba1h3s97m0s866/AADWyYBk8a8S8QNdExMA2w7ga?dl=0)

![image 2018-02-10 12 13 24](https://user-images.githubusercontent.com/914429/36059528-ce08e55e-0e5b-11e8-9390-f33396ac51c9.jpg)
